### ISSUE TITLE
Need to ensure jQuery is available to make this work on Mac Word 2016

### ISSUE THREAD

**Issue by ghost** [OfficeDev/Word-Add-in-SillyStories#1]
This is just feedback - Some observations after trying to get this to work on Mac Word 2016.

It isn't obvious at all how you set up Mac Word so that the Addins group appears in the Insert tab of the Ribbon, or which version of Word is required to make it work. IMO the point about making a _wef_ folder and putting at least one manifest in it should be more prominent in the Office Dev documentation. I could only get going because of the Answer at  http://stackoverflow.com/questions/36221392/office-js-for-word-2016-mac, which was very helpful.

That got me to the point where the HTML appeared in the taskpane, but the dropdown wasn't visible. As a newbie to this stuff it really isn't all that easy to work out what is missing, but in the end it seemed most likely that I didn't have jquery in a place where anything would find it. so I used 'npm install jquery to install it with the other project dependencies. IMO this step should also be in the documentation somewhere. Perhaps it is. But then I thought that the Office js libraries on Microsoft's CDN server would pull that stuff in automatically. Should they?

Still, nice to have a straightforward sample that I could get running fairly easily on both Mac and Windows, thanks.

**Comment by MIchaelMainer** [comment]
@sizaree

Thank you for valuable feedback! I've made a few minor changes to address some of the issues you reported. I'm going through the documentation to find a way to make it clear how to make the add-in appear in Word on the Mac. 

Add-ins don't require that you use JQuery. The Fabric UI dropdown component does require JQuery. It isn't clear from the [documentation](dev.office.com/fabric/components/dropdown) that JQuery is required. 

You make a difference when you provide feedback and we thank you for it.

**Comment by ghost** [comment]
Thanks @MIchaelMainer .
