### ISSUE TITLE
can i upload the manifest.xml in this to Appstore with i updated my own code?

### ISSUE THREAD

**Issue by May-Thae-Sue** [OfficeDev/Word-Add-in-SillyStories#12]
I wrote new UI design by using this file. I retrieved data from server and upload new data to server by using your concept.can i upload the manifest.xml in this to Appstore with i updated my own code?

**Comment by MIchaelMainer** [comment]
You sure can due to the [MIT license](https://github.com/OfficeDev/Word-Add-in-SillyStories/blob/master/LICENSE.txt).
