### ISSUE TITLE
How can i change http://localhost:8080 to https://localhost:3000?

### ISSUE THREAD

**Issue by May-Thae-Sue** [OfficeDev/Word-Add-in-SillyStories#13]
How can i change http://localhost:8080 to https://localhost:3000? 
When i upload my add-ins to appstore, I think it'll be a requirement in one of the uploading rules. Can I change? I don't know how should i do? Please answer and reply me. Thanks.

**Comment by MIchaelMainer** [comment]
Please see https://github.com/OfficeDev/Word-Add-in-SillyStories/blob/master/server.js#L11
