### ISSUE TITLE
Add in not showing

### ISSUE THREAD

**Issue by yairneumann11** [OfficeDev/Word-Add-in-SillyStories#7]
1. I added the manifest file in the specified folder
2. Created the project files.
3. Changed the configuration as explained

I go to the insert tab and click on the add-in button and in the my add-in section the add-in isn't showing, could you please help me?

**Comment by MIchaelMainer** [comment]
Sorry it took us so long to respond. We will try to verify/reproduce that issue and respond here very soon.

**Comment by Rick-Kirkham** [comment]
@yairneumann11 
I am not able to reproduce this issue on a Windows machine. As it happens, the sample was changed recently and the change affects how the add-in launches. Please download the latest version of the add-in and try again. As described in the updated Readme, the add-in is now launched from a button in the ribbon.
