### ISSUE TITLE
HTTPS protocol

### ISSUE THREAD

**Issue by lomagno** [OfficeDev/Word-Add-in-SillyStories#9]
Currently, your add-in is served through http://localhost:8080. I think that your add-in should use the HTTPS protocol, which is required by the add-in infrastructure.

**Comment by MIchaelMainer** [comment]
You are correct. Thank you for bringing this to our attention.

**Comment by Rick-Kirkham** [comment]
I'm going to call this a "Won't Fix". My reasons are: 

-  It works as is and demonstrates the APIs it was intended to show.
- It would be time-consuming to add a certificate creation utility to the sample and configure the node server to use HTTPS.
- It would be irritating to require the user to create the cert and follow instructions for trusting it.
- This is an old sample and may be retired soon.
